set nocompatible              " be iMproved, required
filetype off                  " required

let mapleader = ' ' " Remap leader key

set rtp+=~/.vim/bundle/Vundle.vim " set the runtime path to include Vundle and initialize
call vundle#begin()
  " alternatively, pass a path where Vundle should install plugins
  "call vundle#begin('~/some/path/here')

  Plugin 'VundleVim/Vundle.vim' " let Vundle manage Vundle, required

  Plugin 'tpope/vim-fugitive'
  Plugin 'git://git.wincent.com/command-t.git'
  " The sparkup vim script is in a subdirectory of this repo called vim.
  " Pass the path to set the runtimepath properly.
  Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

  Plugin 'ntpeters/vim-better-whitespace' " Show trailing whitespace and spaces before a tab:
  Plugin 'sheerun/vim-polyglot' " Enable syntax color
  Plugin 'elixir-editors/vim-elixir' " Elixir
  Plugin 'scrooloose/nerdcommenter' " Comments
  Plugin 'w0rp/ale' " Lint and fixers

  " Status tab
  Plugin 'vim-airline/vim-airline'
  Plugin 'vim-airline/vim-airline-themes'

  " Markdown
  Plugin 'godlygeek/tabular'
  Plugin 'plasticboy/vim-markdown'
  Plugin 'junegunn/vim-easy-align'
  Plugin 'JamshedVesuna/vim-markdown-preview'
  Plugin 'mzlogin/vim-markdown-toc' " auto toc
  Plugin 'terryma/vim-multiple-cursors'
  Plugin 'brooth/far.vim'

  Plugin 'romainl/vim-cool' " Remove highlight when move the cursor after a search
  Plugin 'rizzatti/dash.vim' " Dash integration
  Plugin 'mhinz/vim-startify' " Startup buffer
  Plugin 'airblade/vim-rooter' " Change to project root directory automatically

  " fzf
  Plugin 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
  Plugin 'junegunn/fzf.vim'

  " NERDTree
  Plugin 'scrooloose/nerdtree'
  Plugin 'ryanoasis/vim-devicons'
  Plugin 'tiagofumo/vim-nerdtree-syntax-highlight' " colors
  Plugin 'mortonfox/nerdtree-clip'

  Plugin 'easymotion/vim-easymotion' " Quick navigation
  Plugin 'tpope/vim-vinegar' " Filetree
  Plugin 'gcmt/taboo.vim' " Tab rename

  "
  " Colors schemes
  "
  "Plugin 'KeitaNakamura/neodark.vim'
  Plugin 'dracula/vim'
  "Plugin 'joshdick/onedark.vim'
  "Plugin 'rakr/vim-one'
call vundle#end()

"
" Import configs
"
for f in split(glob('~/.vim/config/*.vim'), '\n')
    exe 'source' f
endfor

filetype plugin indent on " required

" Set swp directories
set backupdir=~/.vim/backup//
set directory=~/.vim/swp//
set undodir=~/.vim/undo//

" Set line numbers
set ruler
set number

" Tab to spaces
set expandtab
set tabstop=2

set backspace=indent,eol,start " Fix backspace

set spell spelllang=en_us,es_es " Spell checking

" Indentation
set shiftwidth=2
set autoindent
set smartindent

set hlsearch " Enable highlight when searching

set shiftround " Shift to the next round tab stop.
set shiftwidth=2 " Set auto indent spacing.

"autocmd FileType,BufLeave gitcommit :autocmd! TermOpen * startinsert
"autocmd BufLeave gitcommit startinsert
autocmd BufDelete gitcommit startinsert

" enter and leave terminal mode (insert mode) when switching between buffers
"autocmd BufWinEnter,WinEnter term://* startinsert
"autocmd BufLeave term://* stopinsert

"syntax on
