set nocompatible              " be iMproved, required
filetype off                  " required

let mapleader = ' ' " Remap leader key

" Project switcher
set rtp+=~/.local/share/nvim/plugged/vim-project/
"set rtp+=~/.vim/bundle/vim-project

call plug#begin('~/.local/share/nvim/plugged')
  " alternatively, pass a path where Vundle should install plugins
  "call vundle#begin('~/some/path/here')

  Plug 'VundleVim/Vundle.vim' " let Vundle manage Vundle, required

  Plug 'tpope/vim-fugitive'
  " The sparkup vim script is in a subdirectory of this repo called vim.
  " Pass the path to set the runtimepath properly.
  Plug 'rstacruz/sparkup', {'rtp': 'vim/'}
  Plug 'Asheq/close-buffers.vim' " Clear buffers

  Plug 'amiorin/vim-project' " Projects path switcher

  " Nvim plugins
  Plug 'neovim/nvim-lspconfig'
  " auto install language servers
  Plug 'kabouzeid/nvim-lspinstall'
  Plug 'hrsh7th/nvim-compe'

  " Linters and stuff
  Plug 'ntpeters/vim-better-whitespace' " Show trailing whitespace and spaces before a tab:
  Plug 'scrooloose/nerdcommenter' " Comments

  " Syntax color
  Plug 'elixir-editors/vim-elixir' " Elixir
  Plug 'vim-ruby/vim-ruby'
  Plug 'pangloss/vim-javascript'
  Plug 'mxw/vim-jsx'
  Plug 'leafgarland/typescript-vim'

  " telescope and file search
  Plug 'nvim-lua/popup.nvim'
  Plug 'nvim-lua/plenary.nvim'
  Plug 'nvim-telescope/telescope.nvim'
  Plug 'nvim-telescope/telescope-frecency.nvim'
  Plug 'tami5/sql.nvim' " for telescope-frecency
  Plug 'ahmedkhalf/project.nvim' " for listing projects

  " Status tab
  Plug 'glepnir/galaxyline.nvim' , {'branch': 'main'}

  " Markdown
  Plug 'godlygeek/tabular'
  Plug 'plasticboy/vim-markdown'
  "Plug 'junegunn/vim-easy-align'
  Plug 'JamshedVesuna/vim-markdown-preview'
  Plug 'mzlogin/vim-markdown-toc' " auto toc
  Plug 'terryma/vim-multiple-cursors'

  " Various
  "Plug 'romainl/vim-cool' " Remove highlight when move the cursor after a search
  Plug 'mhinz/vim-startify' " Startup buffer
  Plug 'airblade/vim-rooter' " Change to project root directory automatically
  Plug 'onsails/lspkind-nvim' " Add pictogramas to LSP

  " Substitution
  Plug 'nishigori/increment-activator' " replace boolean values

  " fzf
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
  Plug 'junegunn/fzf.vim'

  " icons
  Plug 'kyazdani42/nvim-web-devicons'

  " tabs
  "Plug 'akinsho/nvim-bufferline.lua'
  Plug 'gcmt/taboo.vim' " Tab rename

  " File tree
  Plug 'kyazdani42/nvim-tree.lua'

  Plug 'easymotion/vim-easymotion' " Quick navigation
  Plug 'tpope/vim-vinegar' " Filetree

  " Snippets
  Plug 'hrsh7th/vim-vsnip'
  Plug 'hrsh7th/vim-vsnip-integ'

  " micromanagement
  Plug 'ActivityWatch/aw-watcher-vim'

  "
  " Colors schemes
  "
  "Plug 'KeitaNakamura/neodark.vim'
  "Plug 'dracula/vim'
  "Plug 'joshdick/onedark.vim'
  "Plug 'rakr/vim-one'
  Plug 'bluz71/vim-nightfly-guicolors'
call plug#end()

"
" Import configs
"
for f in split(glob('~/.vim/config/*.vim'), '\n')
  exe 'source' f
endfor

filetype plugin indent on " required

"
" Set git editor
"
if has('nvim')
  let $GIT_EDITOR = 'nvr -cc split --remote-wait'
endif
autocmd FileType gitcommit,gitrebase,gitconfig set bufhidden=delete


"
" Swap
" "

" Set swp directories
set backupdir=~/.vim/backup//
set directory=~/.vim/swp//
set undodir=~/.vim/undo//

set writebackup " protect against crash-during-write
set nobackup " but do not persist backup after successful write
set backupcopy=auto " use rename-and-write-new method whenever safe

"
" Other stuff
"

set mouse=n

" Set line numbers
set ruler
set number

" Tab to spaces
set expandtab
set tabstop=2

set backspace=indent,eol,start " Fix backspace

set spell spelllang=en_us,es_es " Spell checking

" Indentation
set shiftwidth=2
set autoindent
set smartindent

set hlsearch " Enable highlight when searching

set shiftround " Shift to the next round tab stop.
set shiftwidth=2 " Set auto indent spacing.

" folding
set foldmethod=syntax
set foldlevelstart=20

"autocmd FileType,BufLeave gitcommit :autocmd! TermOpen * startinsert
"autocmd BufLeave gitcommit startinsert
autocmd BufDelete gitcommit startinsert

" enter and leave terminal mode (insert mode) when switching between buffers
"autocmd BufWinEnter,WinEnter term://* startinsert
"autocmd BufLeave term://* stopinsert

"syntax on

set synmaxcol=500
set lazyredraw
set ttyfast
set nocursorcolumn
set nocursorline
set norelativenumber
syntax sync minlines=256
set regexpengine=1
