require 'lsp/config'
require 'plugins/lspkind'
require 'plugins/galaxyline'
--require 'plugins/bufferline'
require 'plugins/nvim_tree'
require 'plugins/telescope_frecency'
require 'plugins/telescope_projects'
