endpoint: https://github.atlassian.net
project: github
login: adrian
password-source: keyring
editor: nvr -s

custom-commands:
  - name: sprint
    help: display issues for active sprint
    args:
      - name: TEMPLATE
        default: list
        type: STRING
        required: false
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list --template {{args.TEMPLATE}} --query "sprint in openSprints() and type != epic and resolution = unresolved and project=$JIRA_PROJECT ORDER BY rank asc, created"
      else
          # otherwise list issues for all project
          {{jira}} list --template {{args.TEMPLATE}} --query "sprint in openSprints() and type != epic and resolution = unresolved ORDER BY rank asc, created"
      fi

  - name: mine
    help: display issues assigned to me
    args:
      - name: TEMPLATE
        default: list
        type: STRING
        required: false
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list --template {{args.TEMPLATE}} --query "sprint in openSprints() and resolution = unresolved and assignee=currentuser() and project = $JIRA_PROJECT ORDER BY priority asc, created"
      else
          # otherwise list issues for all project
          {{jira}} list --template {{args.TEMPLATE}} --query "sprint in openSprints() and resolution = unresolved and assignee=currentuser() ORDER BY priority asc, created"
      fi
